version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/workspace

hooks:
  BeforeInstall:
    - location: build.sh
      runas: root
  ApplicationStart:
    - location: start_application.sh
      timeout: 3600
      runas: root
  ApplicationStop:
     - location: stop_application.sh
       timeout: 10
       runas: root
