version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/workspace

hooks:
  BeforeInstall:
    - location: /root/.nvm/versions/node/v4.4.5/bin/npm install unit.js
    - location: /root/.nvm/versions/node/v4.4.5/bin/npm install pm2
      runas: root
  ApplicationStart:
    - location: /root/.nvm/versions/node/v4.4.5/bin/pm2 start /home/ec2-user/workspace/server.js
      timeout: 3600
      runas: root
  ApplicationStop:
     - location: /root/.nvm/versions/node/v4.4.5/bin/pm2 stop /home/ec2-user/workspace/server.js
       timeout: 10
       runas: root
